/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_BEMATRANG_INS
    @TENBEMAT NVARCHAR(25),
    @MOTA NVARCHAR(100),
    @IDBEMAT VARCHAR(5) = NULL OUTPUT
AS BEGIN TRAN
    SELECT @IDBEMAT = IDBEMAT FROM BEMATRANG
    WHERE IDBEMAT = (SELECT MAX(IDBEMAT) FROM BEMATRANG)

    SET @IDBEMAT = dbo.F_MAKE_ID('RA', @IDBEMAT)

    INSERT INTO BEMATRANG VALUES (@IDBEMAT, @TENBEMAT, @MOTA)
COMMIT TRAN
RETURN 0
GO