/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_CHITIETRANG_INS
    @IDHOSO CHAR(7),
    @IDKEHOACH CHAR(7),
    @IDRANG CHAR(7),
    @IDBEMAT CHAR(7)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM KEHOACHDIEUTRI WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH) BEGIN
        RAISERROR('INVALID KEHOACHDIEUTRI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF EXISTS (SELECT * FROM CHITIETRANG WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDRANG = @IDRANG) BEGIN
        RAISERROR('CHITIETRANG ALREADY EXISTS', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF NOT EXISTS (SELECT * FROM BEMATRANG WHERE IDBEMAT = @IDBEMAT) BEGIN
        RAISERROR('INVALID IDBEMAT', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    INSERT INTO CHITIETRANG
    VALUES (@IDHOSO, @IDKEHOACH, @IDRANG, @IDBEMAT)
COMMIT TRAN
RETURN 0
GO