/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_HOSOBENHNHAN_INS
    @HOTEN NVARCHAR(25),
    @NGAYSINH DATE,
    @GIOITINH INT,
    @EMAIL VARCHAR(30),
    @SDT VARCHAR(11),
    @DIACHI NVARCHAR(50),
    @THONGTINTONGQUAN NVARCHAR(100) = NULL,
    @IDHOSO CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    SELECT @IDHOSO = IDHOSO FROM HOSOBENHNHAN
    WHERE IDHOSO = (SELECT MAX(IDHOSO) FROM HOSOBENHNHAN)

    SET @IDHOSO = dbo.F_MAKE_ID('HS', @IDHOSO)

    INSERT INTO HOSOBENHNHAN
    VALUES (@IDHOSO, @HOTEN, @NGAYSINH, @GIOITINH, @EMAIL, @SDT,
        @DIACHI, @THONGTINTONGQUAN, 0, 0)
COMMIT TRAN
RETURN 0
GO