/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_HOSOBENHNHAN_INS
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATE,
    @GIOITINH INT, -- 0: NAM, 1: NỮ
    @EMAIL VARCHAR(30),
    @SDT VARCHAR(11),
    @DIACHI NVARCHAR(200),
    @THONGTINTONGQUAN NVARCHAR(200) = NULL,
    @IDHOSO CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    SELECT @IDHOSO = IDHOSO FROM HOSOBENHNHAN
    WHERE IDHOSO = (SELECT MAX(IDHOSO) FROM HOSOBENHNHAN)

    SET @IDHOSO = dbo.F_MAKE_ID('HS', @IDHOSO)

    INSERT INTO HOSOBENHNHAN
    VALUES (@IDHOSO, @HOTEN, @NGAYSINH, @GIOITINH, @EMAIL, @SDT,
        @DIACHI, @THONGTINTONGQUAN, 0, 0)
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC USP_HOSOBENHNHAN_UPD
    @IDHOSO CHAR(7),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATE,
    @GIOITINH INT, -- 0: NAM, 1: NỮ
    @EMAIL VARCHAR(30),
    @SDT VARCHAR(11),
    @DIACHI NVARCHAR(200),
    @THONGTINTONGQUAN NVARCHAR(200)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HOSOBENHNHAN WHERE IDHOSO = @IDHOSO) BEGIN
        RAISERROR('INVALID IDHOSO', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @GIOITINH != 0 AND @GIOITINH != 1 BEGIN
        RAISERROR('INVALID GIOITINH', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF @HOTEN IS NULL OR @NGAYSINH IS NULL OR @EMAIL IS NULL OR @SDT IS NULL
        OR @DIACHI IS NULL OR @THONGTINTONGQUAN IS NULL BEGIN
        RAISERROR('INVALID DATA', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    UPDATE HOSOBENHNHAN SET HOTEN = @HOTEN, NGAYSINH = @NGAYSINH,
        GIOITINH = @GIOITINH, EMAIL = @EMAIL, SDT = @SDT, DIACHI = @DIACHI,
        THONGTINTONGQUAN = @THONGTINTONGQUAN
    WHERE IDHOSO = @IDHOSO
COMMIT TRAN
RETURN 0
GO