/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_LICHTUAN_INS
    @IDNHASI CHAR(7),
    @NGAYTRONGTUAN INT, -- 0: MONDAY, 1: TUESDAY, ETC.
    @GIOBATDAU INT,
    @GIOKETTHUC INT,
    @IDLT CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM TAIKHOAN WHERE IDTAIKHOAN = @IDNHASI) BEGIN
        RAISERROR('INVALID IDNHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @NGAYTRONGTUAN < 0 OR @NGAYTRONGTUAN > 6 BEGIN
        RAISERROR('INVALID NGAYTRONGTUAN, MUST BE FROM 0 TO 6', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF @GIOBATDAU >= @GIOKETTHUC BEGIN
        RAISERROR('MUST SATISFY GIOBATDAU < GIOKETTHUC', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    SELECT @IDLT = IDLT FROM LICHTUAN
    WHERE IDLT = (SELECT MAX(IDLT) FROM LICHTUAN
        WHERE IDNHASI = @IDNHASI)

    SET @IDLT = dbo.F_MAKE_ID('HS', @IDLT)

    INSERT INTO LICHTUAN
    VALUES (@IDNHASI, @IDLT, @NGAYTRONGTUAN,
        @GIOBATDAU, @GIOKETTHUC)
COMMIT TRAN
RETURN 0
GO