/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_LICHNGAY_INS
    @IDNHASI CHAR(7),
    @NGAY DATE,
    @GIOBATDAU INT,
    @GIOKETTHUC INT,
    @IDLN CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM TAIKHOAN WHERE IDTAIKHOAN = @IDNHASI) BEGIN
        RAISERROR('INVALID IDNHASI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @GIOBATDAU >= @GIOKETTHUC BEGIN
        RAISERROR('MUST SATISFY GIOBATDAU < GIOKETTHUC', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    SELECT @IDLN = IDLN FROM LICHNGAY
    WHERE IDLN = (SELECT MAX(IDLN) FROM LICHNGAY
        WHERE IDNHASI = @IDNHASI)

    SET @IDLN = dbo.F_MAKE_ID('HS', @IDLN)

    INSERT INTO LICHNGAY
    VALUES (@IDNHASI, @IDLN, @NGAY, @GIOBATDAU, @GIOKETTHUC)
COMMIT TRAN
RETURN 0
GO