/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_MISC_LOGIN
    @TENDANGNHAP VARCHAR(25),
    @MATKHAU VARCHAR(20),
    @IDTAIKHOAN CHAR(7) OUTPUT,
    @LOAITAIKHOAN INT OUTPUT -- 0: NHANVIEN, 1: NHASI, 2: QUANTRIVIEN
AS
    SELECT @IDTAIKHOAN = IDTAIKHOAN, @LOAITAIKHOAN = LOAITAIKHOAN
    FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU
    
    IF (@IDTAIKHOAN IS NULL OR @LOAITAIKHOAN IS NULL) BEGIN
        RAISERROR('INVALID TENDANGNHAP OR MATKHAU', 16, 1)
        RETURN -1
    END

    RETURN 0
GO