/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_RANG_INS
    @TENRANG NVARCHAR(25),
    @VITRI INT,
    @IDRANG VARCHAR(5) = NULL OUTPUT
AS BEGIN TRAN
    IF NOT ((11 <= VITRI AND VITRI <= 18) OR (21 <= VITRI AND VITRI <= 28)
        OR (31 <= VITRI AND VITRI <= 38) OR (41 <= VITRI AND VITRI <= 48)) BEGIN
        RAISERROR('INVALID VITRI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    SELECT @IDRANG = IDRANG FROM RANG
    WHERE IDRANG = (SELECT MAX(IDRANG) FROM RANG)

    SET @IDRANG = dbo.F_MAKE_ID('RA', @IDRANG)

    INSERT INTO RANG VALUES (@IDRANG, @TENRANG, @VITRI)
COMMIT TRAN
RETURN 0
GO