/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_TAIKHOAN_INS
    @TENDANGNHAP NVARCHAR(25),
    @MATKHAU VARCHAR(20),
    @LOAITAIKHOAN INT,
    @HOTEN NVARCHAR(25),
    @NGAYSINH DATE,
    @GIOITINH INT,
    @EMAIL VARCHAR(30),
    @SDT VARCHAR(11),
    @DIACHI NVARCHAR(50),
    @IDTAIKHOAN VARCHAR(5) = NULL OUTPUT
AS BEGIN TRAN
    DECLARE @TYPE CHAR(2)
    IF (@LOAITAIKHOAN = 0) SET @TYPE = 'NV'
    IF (@LOAITAIKHOAN = 1) SET @TYPE = 'NS'
    IF (@LOAITAIKHOAN = 2) SET @TYPE = 'AD'

    SELECT @IDTAIKHOAN = IDTAIKHOAN FROM TAIKHOAN
    WHERE IDTAIKHOAN = (SELECT MAX(IDTAIKHOAN) FROM TAIKHOAN
        WHERE IDTAIKHOAN LIKE @TYPE + '%')

    SET @IDTAIKHOAN = dbo.F_MAKE_ID(@TYPE, @IDTAIKHOAN)

    INSERT INTO TAIKHOAN
    VALUES (@IDTAIKHOAN, @TENDANGNHAP, @MATKHAU, @LOAITAIKHOAN,
        @HOTEN, @NGAYSINH, @GIOITINH, @EMAIL, @SDT, @DIACHI)
COMMIT TRAN
RETURN 0
GO