/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_THANHTOAN_INS
    @IDHOSO CHAR(7),
    @LOAITHANHTOAN INT, -- 0: TIỀN MẶT, 1: ONLINE
    @NGAYTHANHTOAN DATE,
    @GHICHU NVARCHAR(200),
    @IDKEHOACHS VARCHAR(MAX),
    @IDTHANHTOAN CHAR(7) = NULL OUTPUT
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM HOSOBENHNHAN WHERE IDHOSO = @IDHOSO) BEGIN
        RAISERROR('INVALID IDHOSO', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @LOAITHANHTOAN != 0 AND @LOAITHANHTOAN != 1 BEGIN
        RAISERROR('INVALID LOAITHANHTOAN, MUST BE 0 OR 1', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    SELECT @IDTHANHTOAN = IDTHANHTOAN FROM THANHTOAN
    WHERE IDTHANHTOAN = (SELECT MAX(IDTHANHTOAN) FROM THANHTOAN
        WHERE IDHOSO = @IDHOSO)

    SET @IDTHANHTOAN = dbo.F_MAKE_ID('TT', @IDTHANHTOAN)

    INSERT INTO THANHTOAN
    VALUES (@IDHOSO, @IDTHANHTOAN, 0, @TIENDATRA, @LOAITHANHTOAN,
        @NGAYTHANHTOAN, @GHICHU)

    DECLARE @TONGTIEN INT, @IDKEHOACH CHAR(7)
    DECLARE @KEHOACH TABLE(IDKEHOACH CHAR(7))
    INSERT INTO @KEHOACH SELECT [value] FROM string_split(@IDKEHOACHS, ',')

    SELECT @IDKEHOACH = MIN(IDKEHOACH) FROM @KEHOACH
    WHILE @IDKEHOACH IS NOT NULL BEGIN
        IF NOT EXISTS (SELECT * FROM KEHOACHDIEUTRI
            WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH
                AND IDTHANHTOAN IS NULL) BEGIN
            RAISERROR('INVALID IDKEHOACH, OR ITS IDTHANHTOAN IS NOT NULL', 16, 1)
            ROLLBACK TRAN
            RETURN -3
        END

        UPDATE KEHOACHDIEUTRI
        SET IDTHANHTOAN = @IDTHANHTOAN, @TONGTIEN += PHIDIEUTRI
        WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH

        SELECT @IDKEHOACH = MIN(@IDKEHOACH) FROM @KEHOACH
        WHERE IDKEHOACH > @IDKEHOACH
    END

    UPDATE THANHTOAN SET TONGTIEN = @TONGTIEN
    WHERE IDHOSO = @IDHOSO AND IDTHANHTOAN = @IDTHANHTOAN

    UPDATE HOSOBENHNHAN SET TONGTIENDIEUTRI += @TONGTIEN
    WHERE IDHOSO = @IDHOSO
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC USP_THANHTOAN_UPD
    @IDHOSO CHAR(7),
    @IDTHANHTOAN CHAR(7),
    @TIENDATRA INT,
    @LOAITHANHTOAN INT, -- 0: TIỀN MẶT, 1: ONLINE
    @NGAYTHANHTOAN DATE,
    @GHICHU NVARCHAR(200)
AS BEGIN TRAN
    DECLARE @OLDTIENDATRA INT
    SELECT @OLDTIENDATRA = TIENDATRA FROM THANHTOAN
    WHERE IDHOSO = @IDHOSO AND IDTHANHTOAN = @IDTHANHTOAN

    IF @OLDTIENDATRA IS NULL BEGIN
        RAISERROR('INVALID THANHTOAN', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF @TIENDATRA < 0 BEGIN
        RAISERROR('INVALID TIENDATRA', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF @LOAITHANHTOAN != 0 AND @LOAITHANHTOAN != 1 BEGIN
        RAISERROR('INVALID LOAITHANHTOAN, MUST BE 0 OR 1', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    IF @NGAYTHANHTOAN IS NULL OR @GHICHU IS NULL BEGIN
        RAISERROR('INVALID DATA', 16, 1)
        ROLLBACK TRAN
        RETURN -4
    END

    UPDATE THANHTOAN SET TIENDATRA = @TIENDATRA,
        LOAITHANHTOAN = @LOAITHANHTOAN, NGAYTHANHTOAN = @NGAYTHANHTOAN,
        GHICHU = @GHICHU
    WHERE IDHOSO = @IDHOSO AND IDTHANHTOAN = @IDTHANHTOAN

    UPDATE HOSOBENHNHAN
    SET TONGTIENDATHANHTOAN += @TIENDATRA - @OLDTIENDATRA
    WHERE IDHOSO = @IDHOSO
COMMIT TRAN
RETURN 0
GO