/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER PROC USP_TOATHUOC_INS
    @IDHOSO CHAR(7),
    @IDKEHOACH CHAR(7),
    @IDTHUOC CHAR(7),
    @SOLUONG INT = 1
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM KEHOACHDIEUTRI
        WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH) BEGIN
        RAISERROR('INVALID KEHOACHDIEUTRI', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC
        AND SOLUONGTONKHO >= @SOLUONG) BEGIN
        RAISERROR('INVALID IDTHUOC, OR SOLUONGTONKHO IS INSUFFICIENT', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    IF EXISTS (SELECT * FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC) BEGIN
        RAISERROR('TOATHUOC ALREADY EXISTS', 16, 1)
        ROLLBACK TRAN
        RETURN -3
    END

    DECLARE @COST INT
    SET @COST = (SELECT GIATIEN FROM THUOC
        WHERE IDTHUOC = @IDTHUOC) * @SOLUONG

    INSERT INTO TOATHUOC
    VALUES (@IDHOSO, @IDKEHOACH, @IDTHUOC, @SOLUONG)

    UPDATE KEHOACHDIEUTRI SET PHIDIEUTRI += @COST
    WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC USP_TOATHUOC_UPD
    @IDHOSO CHAR(7),
    @IDKEHOACH CHAR(7),
    @IDTHUOC CHAR(7),
    @SOLUONG INT = 1
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC) BEGIN
        RAISERROR('INVALID TOATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    IF NOT EXISTS (SELECT * FROM THUOC WHERE IDTHUOC = @IDTHUOC
        AND SOLUONGTONKHO >= @SOLUONG) BEGIN
        RAISERROR('INVALID MATHUOC, OR SOLUONGTONKHO IS INSUFFICIENT', 16, 1)
        ROLLBACK TRAN
        RETURN -2
    END

    DECLARE @DIFFSOLUONG INT
    SELECT @DIFFSOLUONG = SOLUONG FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC

    SET @DIFFSOLUONG = @SOLUONG - @DIFFSOLUONG
    SET @DIFFCOST = (SELECT GIATIEN FROM THUOC
        WHERE IDTHUOC = @IDTHUOC) * @DIFFSOLUONG

    UPDATE TOATHUOC SET SOLUONG = @SOLUONG WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC

    UPDATE THUOC SET SOLUONGTONKHO -= @DIFFSOLUONG WHERE IDTHUOC = @IDTHUOC

    UPDATE KEHOACHDIEUTRI SET PHIDIEUTRI += @DIFFCOST
    WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC USP_TOATHUOC_DEL
    @IDHOSO CHAR(7),
    @IDKEHOACH CHAR(7),
    @IDTHUOC CHAR(7)
AS BEGIN TRAN
    IF NOT EXISTS (SELECT * FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC) BEGIN
        RAISERROR('INVALID TOATHUOC', 16, 1)
        ROLLBACK TRAN
        RETURN -1
    END

    DECLARE @SOLUONG INT, @COST INT
    SELECT @SOLUONG = SOLUONG FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC

    SET @COST = (SELECT GIATIEN FROM THUOC WHERE IDTHUOC = @IDTHUOC)
        * @SOLUONG

    DELETE FROM TOATHUOC WHERE IDHOSO = @IDHOSO
        AND IDKEHOACH = @IDKEHOACH AND IDTHUOC = @IDTHUOC

    UPDATE THUOC SET SOLUONGTONKHO += @SOLUONG WHERE IDTHUOC = @IDTHUOC

    UPDATE KEHOACHDIEUTRI SET PHIDIEUTRI -= @COST
    WHERE IDHOSO = @IDHOSO AND IDKEHOACH = @IDKEHOACH
COMMIT TRAN
RETURN 0
GO