/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

CREATE OR ALTER FUNCTION F_CHK_NHASI_FREE
    (@IDNHASI CHAR(7), @NGAY DATE, @GIO INT)
RETURNS BIT AS BEGIN
    IF EXISTS (SELECT * FROM LICHHEN WHERE IDNHASI = @IDNHASI
        AND NGAY = @NGAY AND ABS(GIO - @GIO) <= 60)
    OR EXISTS (SELECT * FROM LICHHEN WHERE IDTROKHAM = @IDNHASI
        AND NGAY = @NGAY AND ABS(GIO - @GIO) <= 60) RETURN 0
    
    IF EXISTS (SELECT * FROM LICHNGAY WHERE IDNHASI = @IDNHASI
        AND NGAY = @NGAY AND GIOBATDAU <= @GIO AND @GIO <= GIOKETTHUC)
        RETURN 1
    
    IF EXISTS (SELECT * FROM LICHTUAN WHERE IDNHASI = @IDNHASI
        AND NGAYTRONGTUAN = DATENAME(WEEKDAY, @NGAY)
        AND GIOBATDAU <= @GIO AND @GIO <= GIOKETTHUC) RETURN 1
    
    IF EXISTS (SELECT * FROM LICHTHANG WHERE IDNHASI = @IDNHASI
        AND NGAYTRONGTHANG = DAY(@NGAY)) RETURN 1

    RETURN 0
END
GO