/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE master
GO

IF DB_ID('NC03_QLNhaKhoa') IS NOT NULL
BEGIN
    ALTER DATABASE [NC03_QLNhaKhoa]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [NC03_QLNhaKhoa]
END
GO

CREATE DATABASE [NC03_QLNhaKhoa]
GO
USE [NC03_QLNhaKhoa]
GO

CREATE TABLE TAIKHOAN (
    IDTAIKHOAN CHAR(7),
    TENDANGNHAP VARCHAR(25),
    MATKHAU VARCHAR(20),
    LOAITAIKHOAN INT, -- 0: NHANVIEN, 1: NHASI, 2: QUANTRIVIEN
    HOTEN NVARCHAR(25),
    NGAYSINH DATE,
    GIOITINH INT, -- 0: NAM, 1: NỮ
    EMAIL VARCHAR(30),
    SDT VARCHAR(11),
    DIACHI NVARCHAR(100),

    CONSTRAINT PK_TAIKHOAN
    PRIMARY KEY(IDTAIKHOAN),

    CONSTRAINT CHK_TAIKHOAN_LOAITAIKHOAN
    CHECK (LOAITAIKHOAN = 0 OR LOAITAIKHOAN = 1 OR LOAITAIKHOAN = 2),

    CONSTRAINT CHK_TAIKHOAN_GIOITINH
    CHECK (GIOITINH = 0 OR GIOITINH = 1)
)

CREATE TABLE LICHNGAY (
    IDNHASI CHAR(7),
    IDLN CHAR(7),
    NGAY DATE,
    GIOBATDAU INT,
    GIOKETTHUC INT,

    CONSTRAINT PK_LICHNGAY
    PRIMARY KEY(IDNHASI, IDLN),

    CONSTRAINT FK_LICHNGAY_TAIKHOAN
    FOREIGN KEY(IDNHASI)
    REFERENCES TAIKHOAN,

    CONSTRAINT CHK_LICHNGAY_GIOBATDAU_GIOKETTHUC
    CHECK (GIOBATDAU >= 0 AND GIOKETTHUC >= 0)
)

CREATE TABLE LICHTUAN (
    IDNHASI CHAR(7),
    IDLT CHAR(7),
    NGAYTRONGTUAN INT, -- 0: MONDAY, 1: TUESDAY, ETC.
    GIOBATDAU INT,
    GIOKETTHUC INT,

    CONSTRAINT PK_LICHTUAN
    PRIMARY KEY(IDNHASI, IDLT),

    CONSTRAINT FK_LICHTUAN_TAIKHOAN
    FOREIGN KEY(IDNHASI)
    REFERENCES TAIKHOAN,

    CONSTRAINT CHK_LICHTUAN_GIOBATDAU_GIOKETTHUC
    CHECK (GIOBATDAU >= 0 AND GIOKETTHUC >= 0)
)

CREATE TABLE LICHTHANG (
    IDNHASI CHAR(7),
    IDLT CHAR(7),
    NGAYTRONGTHANG INT,

    CONSTRAINT PK_LICHTHANG
    PRIMARY KEY(IDNHASI, IDLT),

    CONSTRAINT FK_LICHTHANG_TAIKHOAN
    FOREIGN KEY(IDNHASI)
    REFERENCES TAIKHOAN,
)

CREATE TABLE HOSOBENHNHAN (
    IDHOSO CHAR(7),
    HOTEN NVARCHAR(25),
    NGAYSINH DATE,
    GIOITINH INT, -- 0: NAM, 1: NỮ
    EMAIL VARCHAR(30),
    SDT VARCHAR(11),
    DIACHI NVARCHAR(100),
    THONGTINTONGQUAN NVARCHAR(100),
    TONGTIENDIEUTRI INT,
    TONGTIENDATHANHTOAN INT,

    CONSTRAINT PK_HOSOBENHNHAN
    PRIMARY KEY(IDHOSO),

    CONSTRAINT CHK_HOSOBENHNHAN_GIOITINH
    CHECK (GIOITINH = 0 OR GIOITINH = 1),

    CONSTRAINT CHK_HOSOBENHNHAN_TONGTIENDIEUTRI_TONGTIENDATHANHTOAN
    CHECK (TONGTIENDIEUTRI >= 0 AND TONGTIENDATHANHTOAN >= 0)
)

CREATE TABLE GHICHU (
    IDHOSO CHAR(7),
    IDGHICHU CHAR(7),
    THONGTIN NVARCHAR(100),
    NGAYCAPNHAT DATE,
    LOAIGHICHU INT, -- 0: TÌNH TRẠNG DỊ ỨNG, 1: CHỐNG CHỈ ĐỊNH THUỐC

    CONSTRAINT PK_GHICHU
    PRIMARY KEY(IDHOSO, IDGHICHU),

    CONSTRAINT FK_GHICHU_HOSOBENHNHAN
    FOREIGN KEY(IDHOSO)
    REFERENCES HOSOBENHNHAN,

    CONSTRAINT CHK_GHICHU_LOAIGHICHU
    CHECK (LOAIGHICHU = 0 OR LOAIGHICHU = 1),
)

CREATE TABLE PHONGKHAM (
    IDPHONGKHAM CHAR(7),
    EMAIL VARCHAR(30),
    SDT VARCHAR(11),
    DIACHI NVARCHAR(100),
    GIOMOCUA INT,
    GIODONGCUA INT,

    CONSTRAINT PK_PHONGKHAM
    PRIMARY KEY(IDPHONGKHAM),

    CONSTRAINT CHK_PHONGKHAM_GIOMOCUA_GIODONGCUA
    CHECK (GIOMOCUA >= 0 AND GIODONGCUA >= 0)
)

CREATE TABLE LICHHEN (
    IDHOSO CHAR(7),
    IDLICHHEN CHAR(7),
    NGAY DATE,
    GIO INT,
    TINHTRANG INT, -- 0: CUỘC HẸN MỚI, 1: TÁI KHÁM
    GHICHU NVARCHAR(100),
    IDPHONGKHAM CHAR(7),
    IDNHASI CHAR(7),
    IDTROKHAM CHAR(7),
    IDNHANVIENDAT CHAR(7),

    CONSTRAINT PK_LICHHEN
    PRIMARY KEY(IDHOSO, IDLICHHEN),

    CONSTRAINT FK_LICHHEN_HOSOBENHNHAN
    FOREIGN KEY(IDHOSO)
    REFERENCES HOSOBENHNHAN,

    CONSTRAINT FK_LICHHEN_PHONGKHAM
    FOREIGN KEY(IDPHONGKHAM)
    REFERENCES PHONGKHAM,

    CONSTRAINT FK_LICHHEN_TAIKHOAN_IDNHASI
    FOREIGN KEY(IDNHASI)
    REFERENCES TAIKHOAN,
    CONSTRAINT FK_LICHHEN_TAIKHOAN_IDTROKHAM
    FOREIGN KEY(IDTROKHAM)
    REFERENCES TAIKHOAN,
    CONSTRAINT FK_LICHHEN_TAIKHOAN_IDNHANVIENDAT
    FOREIGN KEY(IDNHANVIENDAT)
    REFERENCES TAIKHOAN,

    CONSTRAINT CHK_LICHHEN_GIO
    CHECK (GIO >= 0),

    CONSTRAINT CHK_LICHHEN_TINHTRANG
    CHECK (TINHTRANG = 0 OR TINHTRANG = 1)
)

CREATE TABLE DANHMUC (
    IDDANHMUC CHAR(7),
    TENDANHMUC NVARCHAR(25),

    CONSTRAINT PK_DANHMUC
    PRIMARY KEY(IDDANHMUC)
)

CREATE TABLE LIEUTRINH (
    IDLIEUTRINH CHAR(7),
    TENLIEUTRINH NVARCHAR(25),
    GIA INT,
    IDDANHMUC CHAR(7),

    CONSTRAINT PK_LIEUTRINH
    PRIMARY KEY(IDLIEUTRINH),

    CONSTRAINT FK_LIEUTRINH_DANHMUC
    FOREIGN KEY(IDDANHMUC)
    REFERENCES DANHMUC,

    CONSTRAINT CHK_LIEUTRINH_GIA
    CHECK (GIA >= 0)
)

CREATE TABLE THANHTOAN (
    IDHOSO CHAR(7),
    IDTHANHTOAN CHAR(7),
    TONGTIEN INT,
    TIENDATRA INT,
    LOAITHANHTOAN INT, -- 0: TIỀN MẶT, 1: ONLINE
    NGAYTHANHTOAN DATE,
    GHICHU NVARCHAR(100),

    CONSTRAINT PK_THANHTOAN
    PRIMARY KEY(IDHOSO, IDTHANHTOAN),

    CONSTRAINT FK_THANHTOAN_HOSOBENHNHAN
    FOREIGN KEY(IDHOSO)
    REFERENCES HOSOBENHNHAN,

    CONSTRAINT CHK_THANHTOAN_TONGTIEN_TIENDATRA
    CHECK (TONGTIEN >= 0 AND TIENDATRA >= 0)
)

CREATE TABLE KEHOACHDIEUTRI (
    IDHOSO CHAR(7),
    IDKEHOACH CHAR(7),
    MOTA NVARCHAR(100),
    NGAYDIEUTRI DATE,
    GHICHU NVARCHAR(100),
    TRANGTHAIDIEUTRI INT, -- 0: KẾ HOẠCH (XANH DƯƠNG),
        -- 1: ĐÃ HOÀN THÀNH (XANH LÁ), 2: ĐÃ HỦY (VÀNG)
    PHIDIEUTRI INT,
    LOAITHANHTOAN INT, -- 0: TIỀN MẶT, 1: ONLINE
    IDNHASI CHAR(7),
    IDTROKHAM CHAR(7),
    IDLIEUTRINH CHAR(7),
    IDTHANHTOAN CHAR(7),

    CONSTRAINT PK_KEHOACHDIEUTRI
    PRIMARY KEY(IDHOSO, IDKEHOACH),

    CONSTRAINT FK_KEHOACHDIEUTRI_HOSOBENHNHAN
    FOREIGN KEY(IDHOSO)
    REFERENCES HOSOBENHNHAN,

    CONSTRAINT FK_KEHOACHDIEUTRI_TAIKHOAN_IDNHASI
    FOREIGN KEY(IDNHASI)
    REFERENCES TAIKHOAN,
    CONSTRAINT FK_KEHOACHDIEUTRI_TAIKHOAN_IDTROKHAM
    FOREIGN KEY(IDTROKHAM)
    REFERENCES TAIKHOAN,

    CONSTRAINT FK_KEHOACHDIEUTRI_LIEUTRINH
    FOREIGN KEY(IDLIEUTRINH)
    REFERENCES LIEUTRINH,

    CONSTRAINT FK_KEHOACHDIEUTRI_THANHTOAN
    FOREIGN KEY(IDHOSO, IDTHANHTOAN)
    REFERENCES THANHTOAN,

    CONSTRAINT CHK_KEHOACHDIEUTRI_TRANGTHAIDIEUTRI
    CHECK (TRANGTHAIDIEUTRI = 0 OR TRANGTHAIDIEUTRI = 1 OR TRANGTHAIDIEUTRI = 2),

    CONSTRAINT CHK_KEHOACHDIEUTRI_PHIDIEUTRI
    CHECK (PHIDIEUTRI >= 0),

    CONSTRAINT CHK_KEHOACHDIEUTRI_LOAITHANHTOAN
    CHECK (LOAITHANHTOAN = 0 OR LOAITHANHTOAN = 1)
)

CREATE TABLE RANG (
    IDRANG CHAR(7),
    TENRANG NVARCHAR(25),
    VITRI INT,

    CONSTRAINT PK_RANG
    PRIMARY KEY(IDRANG),

    CONSTRAINT CHK_RANG_VITRI
    CHECK ((11 <= VITRI AND VITRI <= 18) OR (21 <= VITRI AND VITRI <= 28)
        OR (31 <= VITRI AND VITRI <= 38) OR (41 <= VITRI AND VITRI <= 48))
)

CREATE TABLE BEMATRANG (
    IDBEMAT CHAR(7),
    TENBEMAT NVARCHAR(25),
    MOTA NVARCHAR(100),

    CONSTRAINT PK_BEMATRANG
    PRIMARY KEY(IDBEMAT)
)

CREATE TABLE CHITIETRANG (
    IDHOSO CHAR(7),
    IDKEHOACH CHAR(7),
    IDRANG CHAR(7),
    IDBEMAT CHAR(7),

    CONSTRAINT PK_CHITIETRANG
    PRIMARY KEY(IDHOSO, IDKEHOACH, IDRANG),

    CONSTRAINT FK_CHITIETRANG_KEHOACHDIEUTRI
    FOREIGN KEY(IDHOSO, IDKEHOACH)
    REFERENCES KEHOACHDIEUTRI,

    CONSTRAINT FK_CHITIETRANG_RANG
    FOREIGN KEY(IDRANG)
    REFERENCES RANG,

    CONSTRAINT FK_CHITIETRANG_BEMATRANG
    FOREIGN KEY(IDBEMAT)
    REFERENCES BEMATRANG
)

CREATE TABLE THUOC (
    IDTHUOC CHAR(7),
    TENTHUOC NVARCHAR(25),
    DONVITINH INT, -- 0: VIÊN, 1: GÓI, 2: HỘP
    CHIDINH NVARCHAR(50),
    SOLUONGTONKHO INT,
    NGAYHETHAN DATE,
    GIATIEN INT,

    CONSTRAINT PK_THUOC
    PRIMARY KEY(IDTHUOC),

    CONSTRAINT CHK_THUOC_DONVITINH
    CHECK (DONVITINH = 0 OR DONVITINH = 1 OR DONVITINH = 2),

    CONSTRAINT CHK_THUOC_SOLUONGTONKHO_GIATIEN
    CHECK (SOLUONGTONKHO >= 0 AND GIATIEN >= 0)
)

CREATE TABLE TOATHUOC (
    IDHOSO CHAR(7),
    IDKEHOACH CHAR(7),
    IDTHUOC CHAR(7),
    SOLUONG INT,

    CONSTRAINT PK_TOATHUOC
    PRIMARY KEY(IDHOSO, IDKEHOACH, IDTHUOC),

    CONSTRAINT FK_TOATHUOC_KEHOACHDIEUTRI
    FOREIGN KEY(IDHOSO, IDKEHOACH)
    REFERENCES KEHOACHDIEUTRI,

    CONSTRAINT FK_TOATHUOC_THUOC
    FOREIGN KEY(IDTHUOC)
    REFERENCES THUOC,

    CONSTRAINT CHK_TOATHUOC_SOLUONG
    CHECK (SOLUONG >= 0)
)