/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

-- TAIKHOAN
CREATE INDEX IDX_TAIKHOAN_LOAITAIKHOAN ON TAIKHOAN(LOAITAIKHOAN)

-- HOSOBENHNHAN
CREATE INDEX IDX_HOSOBENHNHAN_HOTEN ON HOSOBENHNHAN(HOTEN)
CREATE INDEX IDX_HOSOBENHNHAN_SDT ON HOSOBENHNHAN(SDT)

-- LICHHEN
CREATE INDEX IDX_LICHHEN_IDNHASI_NGAY ON LICHHEN(IDNHASI, NGAY)

-- KEHOACHDIEUTRI
CREATE INDEX IDX_KEHOACHDIEUTRI_IDNHASI_NGAYDIEUTRI
ON KEHOACHDIEUTRI(IDNHASI, NGAYDIEUTRI)

-- THUOC
CREATE INDEX IDX_THUOC_TENTHUOC ON THUOC(TENTHUOC)

/* UNCHECKED INDICES
 */
--IDX6
--Lọc cuộc hẹn riêng của nha sĩ
CREATE INDEX IDX_LICHHEN_LICHRIENGBACSI
ON LICHHEN(IDNHASI, IDNHANVIENDAT, NGAY)