/* 21HTTT1 - 21CLC1.CSDLNC.03
 * 21127004 - Trần Nguyễn An Phong
 * 21127135 - Diệp Hữu Phúc
 * 21127296 - Đặng Hà Huy
 * 21127315 - Nguyễn Gia Khánh
 * 21127712 - Lê Quang Trường
 */
USE [NC03_QLNhaKhoa]
GO

-- TAIKHOAN
CREATE INDEX IDX_TAIKHOAN_LOAITAIKHOAN ON TAIKHOAN(LOAITAIKHOAN)
INCLUDE(HOTEN, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI)
GO

-- HOSOBENHNHAN
CREATE INDEX IDX_HOSOBENHNHAN_HOTEN ON HOSOBENHNHAN(HOTEN)
INCLUDE(NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, THONGTINTONGQUAN,
    TONGTIENDIEUTRI, TONGTIENDATHANHTOAN)

CREATE INDEX IDX_HOSOBENHNHAN_SDT ON HOSOBENHNHAN(SDT)
INCLUDE(HOTEN, NGAYSINH, GIOITINH, EMAIL, DIACHI, THONGTINTONGQUAN,
    TONGTIENDIEUTRI, TONGTIENDATHANHTOAN)
GO

-- LICHHEN
CREATE INDEX IDX_LICHHEN_NGAY ON LICHHEN(NGAY)
INCLUDE(TINHTRANG, IDPHONGKHAM)

CREATE INDEX IDX_LICHHEN_IDNHASI_NGAY ON LICHHEN(IDNHASI, NGAY)
INCLUDE(GIO, TINHTRANG, GHICHU, IDPHONGKHAM, IDTROKHAM, IDNHANVIENDAT)

CREATE INDEX IDX_LICHHEN_IDTROKHAM_NGAY ON LICHHEN(IDTROKHAM, NGAY)
INCLUDE(GIO, TINHTRANG, GHICHU, IDPHONGKHAM, IDNHASI, IDNHANVIENDAT)

CREATE INDEX IDX_LICHHEN_IDNHASI_IDNHANVIENDAT_NGAY
ON LICHHEN(IDNHASI, IDNHANVIENDAT, NGAY)
INCLUDE(GIO, TINHTRANG, GHICHU, IDPHONGKHAM, IDTROKHAM)
GO

-- THANHTOAN
CREATE INDEX IDX_THANHTOAN_NGAYTHANHTOAN ON THANHTOAN(NGAYTHANHTOAN)
INCLUDE(TONGTIEN, TIENDATRA, LOAITHANHTOAN)
GO

-- KEHOACHDIEUTRI
CREATE INDEX IDX_KEHOACHDIEUTRI_NGAYDIEUTRI ON KEHOACHDIEUTRI(NGAYDIEUTRI)
INCLUDE(TRANGTHAIDIEUTRI, PHIDIEUTRI, LOAITHANHTOAN)

CREATE INDEX IDX_KEHOACHDIEUTRI_IDNHASI_NGAYDIEUTRI
ON KEHOACHDIEUTRI(IDNHASI, NGAYDIEUTRI)
INCLUDE(MOTA, GHICHU, TRANGTHAIDIEUTRI, IDTROKHAM, IDLIEUTRINH)

CREATE INDEX IDX_KEHOACHDIEUTRI_IDTROKHAM_NGAYDIEUTRI
ON KEHOACHDIEUTRI(IDTROKHAM, NGAYDIEUTRI)
INCLUDE(MOTA, GHICHU, TRANGTHAIDIEUTRI, IDNHASI, IDLIEUTRINH)
GO

-- THUOC
CREATE INDEX IDX_THUOC_TENTHUOC ON THUOC(TENTHUOC)
INCLUDE(DONVITINH, CHIDINH, SOLUONGTONKHO, NGAYHETHAN, GIATIEN)
GO